### ISSUE TITLE
Can't use special characters in route

### ISSUE THREAD

**Issue by DeanvanZwietering** [doublethreedigital/runway#104]
### Bug Description

When creating a route in config/runway.php it removes the special characters from the path

### Steps to reproduce

1. Make a route that uses '?' and/or '='
2. Run php please runway:rebuild-uris
3. When you try to use {{ url }} in your antlers.html file it will be missing it's special characters

### Environment

Statamic 3.2.23 Pro
Laravel 8.69.0
PHP 7.4.23
doublethreedigital/runway 2.1.32

**Comment by duncanmcclean** [comment]
Thanks for opening an issue.

However, I've decided that I'm not going to support the use of special characters in URIs. Statamic itself doesn't support them for entries either. 

If you need to use a URL with query parameters to return your models, I'd recommend that you use a custom controller.
