### ISSUE TITLE
N+1 issue on listing page

### ISSUE THREAD

**Issue by edalzell** [doublethreedigital/runway#113]
### Bug Description

If you have a model that has several relationships, you get many many single queries:

<img width="791" alt="CleanShot 2022-02-04 at 15 55 18@2x" src="https://user-images.githubusercontent.com/6069653/152618596-c02edcc3-2e71-4952-a507-060149ae0362.png">

<img width="797" alt="CleanShot 2022-02-04 at 15 58 23@2x" src="https://user-images.githubusercontent.com/6069653/152618656-a92988b9-1ee6-4e46-9cd0-930c662bf388.png">

### Steps to reproduce

Have models with several (4 in my case) relationship fields. Then list them.

### Environment

```
Statamic 3.2.32 Pro
Laravel 8.82.0
PHP 8.0.15
aryehraber/statamic-captcha 1.7.0
aryehraber/statamic-uuid 2.0.3
doublethreedigital/runway 2.2.0
edalzell/forma 1.0
edalzell/private-eye dev-main
jonassiewertsen/statamic-livewire 2.7.1
statamic/seo-pro 2.3.2
transformstudios/events 3.3.3
transformstudios/front 1.9.1
transformstudios/gated dev-main
transformstudios/magic-link dev-main
transformstudios/memorial dev-main
transformstudios/price-of dev-main
transformstudios/review 3.1.1
transformstudios/shopify dev-main
transformstudios/simple dev-main
transformstudios/stripe dev-main
transformstudios/takeover-redirects dev-main
```

**Comment by edalzell** [comment]
thinking about this, you could have folks define the relationships in the config?

Or maybe parse the blueprint for the hasmany/belongsto/etc to get them automatically?

**Comment by edalzell** [comment]
Perhaps use this package to find them all: https://github.com/beyondcode/laravel-query-detector

**Comment by duncanmcclean** [comment]
I imagine I'll go down the road of parsing the blueprint for relationships, then eager load those relations.
