### ISSUE TITLE
Generating blueprints

### ISSUE THREAD

**Issue by HazemMohamed252** [doublethreedigital/runway#122]
### What would you like to see added?

Add new module in sidebar

### Is there a workaround you can use in the meantime?

php please runway:generate-blueprints resource-handle
Generating blueprints...

   DoubleThreeDigital\Runway\Exceptions\ResourceNotFound

  Runway could not find [resource-handle]. Please ensure its configured properly and you're using the correct handle.

  at D:\develop\sta\vendor\doublethreedigital\runway\src\Runway.php:82
     78▕     {
     79▕         $resource = collect(static::$resources)->get($resourceHandle);
     80▕
     81▕         if (! $resource) {
  ➜  82▕             throw new ResourceNotFound($resourceHandle);
     83▕         }
     84▕
     85▕         return $resource;
     86▕     }

  1   D:\develop\sta\vendor\doublethreedigital\runway\src\Console\Commands\GenerateBlueprint.php:140
      DoubleThreeDigital\Runway\Runway::findResource("resource-handle")

  2   D:\develop\sta\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:36
      DoubleThreeDigital\Runway\Console\Commands\GenerateBlueprint::handle()

### Priority wise - where's this feature for you?

Nice to have

**Comment by duncanmcclean** [comment]
`resource-handle` is a placeholder in the documentation. Replace it with the name of your model.

**Comment by HazemMohamed252** [comment]
Thanks so much
