### ISSUE TITLE
Is it possible to use this for translatable models?

### ISSUE THREAD

**Issue by edwwaarrdd** [doublethreedigital/runway#125]
### What's the issue you're running into?

I was wondering if it would be possible to use this plugin for translatable models. With something like 
https://github.com/spatie/laravel-translatable or https://github.com/Astrotomic/laravel-translatable .
I know this is maybe out of scope of the plugin but was wondering if anyone has tried it before?

Thanks in advance!

### Steps to reproduce

Fresh install of Statamic with this package and some translatable models.

### Environment

Statamic 3.3.0-beta.2 Pro
Laravel 9.1.0
PHP 8.1.3
doublethreedigital/runway 2.3.0
statamic/eloquent-driver 0.2.0

**Comment by duncanmcclean** [comment]
Hey! Thanks for opening an issue.

Unfortunately, I don't know of anyone who's used that package alongside Runway. Maybe give it a go and see if it'll work?

As this is outside of the scope of this addon, I'm going to close this issue. Feel free to continue the discussion though.
