### ISSUE TITLE
Can't delete related entries in stack

### ISSUE THREAD

**Issue by edalzell** [doublethreedigital/runway#126]
### Bug Description

We have Orphans  that `HasMany` Updates. We've displayed them in a section tab.

Can't delete them. When I click the Delete, nothing happens.

<img width="1242" alt="CleanShot 2022-03-04 at 11 46 56@2x" src="https://user-images.githubusercontent.com/6069653/156831607-6f27064a-d980-4492-8f07-41db0e4bc447.png">

### Steps to reproduce

1. have a resource w/ a `HasMany` relationship
2. display them in the CP via the `HasMany` field.
3. Attempt to delete them.

### Environment

```
Statamic 3.2.35 Pro
Laravel 8.83.3
PHP 8.1.3
aryehraber/statamic-captcha 1.7.0
aryehraber/statamic-uuid 2.0.3
doublethreedigital/duplicator 2.1.1
doublethreedigital/runway 2.3.0
edalzell/forma 1.0
edalzell/private-eye dev-main
jonassiewertsen/statamic-livewire 2.7.1
statamic/seo-pro 2.3.2
transformstudios/events 3.3.3
transformstudios/front 1.9.2
transformstudios/gated dev-main
transformstudios/magic-link dev-main
transformstudios/memorial dev-main
transformstudios/review 3.2.1
transformstudios/simple dev-main
transformstudios/takeover-redirects dev-main
```

**Comment by duncanmcclean** [comment]
Does this happen outside of stacks as well?

**Comment by edalzell** [comment]
Bad description, not in a stack, standard view.

**Comment by duncanmcclean** [comment]
Gotcha! Any console errors? I'll take a look tomorrow (probably!)

**Comment by edalzell** [comment]
I'm an idiot, it does work, found another issue.
