### ISSUE TITLE
No Confirm when deleting a `HasMany` 

### ISSUE THREAD

**Issue by edalzell** [doublethreedigital/runway#127]
### Bug Description

We have Orphans that `HasMany` Updates. We view those in the CP via the `HasMany` fieldtype.

When we delete an Update, no confirmation is shown.

### Steps to reproduce

1. Have resource w/ a `HasMany`
2. Have some relation data
3. delete it

See video: https://cln.sh/F3v81P

### Environment

Statamic 3.2.35 Pro
Laravel 8.83.3
PHP 8.1.3
aryehraber/statamic-captcha 1.7.0
aryehraber/statamic-uuid 2.0.3
doublethreedigital/duplicator 2.1.1
doublethreedigital/runway 2.3.0
edalzell/forma 1.0
edalzell/private-eye dev-main
jonassiewertsen/statamic-livewire 2.7.1
statamic/seo-pro 2.3.2
transformstudios/events 3.3.3
transformstudios/front 1.9.2
transformstudios/gated dev-main
transformstudios/magic-link dev-main
transformstudios/memorial dev-main
transformstudios/review 3.2.1
transformstudios/simple dev-main
transformstudios/takeover-redirects dev-main

**Comment by duncanmcclean** [comment]
What sort of thing are you expecting? That seems fine to me...

**Comment by edalzell** [comment]
> What sort of thing are you expecting? That seems fine to me...

<img width="1692" alt="CleanShot 2022-03-04 at 12 34 41@2x" src="https://user-images.githubusercontent.com/6069653/156837661-f93cb3b1-0a5c-472f-99ad-04e8cc7b7141.png">

That's what you see when you delete from the Updates listing itself.

**Comment by duncanmcclean** [comment]
When you delete from any other relationship fieldtype (which is what this is), you don't get a confirmation prompt...
