### ISSUE TITLE
Runway resource

### ISSUE THREAD

**Issue by HazemMohamed252** [doublethreedigital/runway#128]
### What's the issue you're running into?

Issue in generating migrations from your blueprints

### Steps to reproduce

After i created model and config the runway resources and try to run the migration using : php please runway:generate-migrations resource-handle and replaced resource-handle with my model i got this error : Runway could not find [Order]. Please ensure its configured properly and you're using the correct handle. How to fix it please

### Environment

Statamic 3.2.37 Pro
Laravel 8.83.4
PHP 7.4.11
doublethreedigital/runway 2.3.0
doublethreedigital/simple-commerce 2.3.70

**Comment by duncanmcclean** [comment]
What if you do this (note the lowercase O)?

```
php please runway:generate-migrations order
```

**Comment by HazemMohamed252** [comment]
Oh the issue was due to the lowercase. Many thanks
