### ISSUE TITLE
Runway blueprints

### ISSUE THREAD

**Issue by HazemMohamed252** [doublethreedigital/runway#129]
### Bug Description

When i create new resource and create new blueprint using the CLI , i go to CP and open the blueprints link i can not find the new resource i have created. I want to customize the fields for this new resource (new nav). For example : i have created new resource: Products and i want to customize the fields on it but i guess to open the blueprints and view it but nothing appears. How to ifx this

### Steps to reproduce

1. Create new model : Product
2. Generate new blueprint for it using : php please runway:generate-blueprints
3. switch to blueprint page to see it so nothing appears

### Environment

Statamic 3.2.37 Pro
Laravel 8.83.4
PHP 7.4.11
doublethreedigital/runway 2.3.0
doublethreedigital/simple-commerce 2.3.70

**Comment by duncanmcclean** [comment]
Addons can't add blueprints to the list in the CP, at least not yet, it's a feature request at the moment though.

Please [review the documentation](https://runway.duncanmcclean.com/resources#content-resource-blueprints) on how to setup blueprints for resources.

**Comment by HazemMohamed252** [comment]
But how can i move the new nav from content section to be under TOOLS section. Is this available ?

**Comment by duncanmcclean** [comment]
Add the following to your `AppServiceProvider`'s `boot` method & replace `attachment` in the URL with the singular/lowercase version of your model name.

```php
\Statamic\Statamic::booted(function () {
            \Statamic\Facades\CP\Nav::extend(function ($nav) {
                $nav->content('Attachments')
                    ->icon('assets')
                    ->url('/cp/runway/attachment')
                    ->section('Tools');
            });
});
```
