### ISSUE TITLE
Resource view

### ISSUE THREAD

**Issue by HazemMohamed252** [doublethreedigital/runway#130]
### What's the issue you're running into?

After create new nav using the resource, i can't find the views for this resource to handle it with many action or anything else. For example create new resource call it : Types and then create the related blueprint. Now i want to make view for it and because i don not know where to show the results or where it is saved

### Steps to reproduce

1. Create new resource for example : Types
2. Create the related blueprint

### Environment

Statamic 3.2.37 Pro
Laravel 8.83.4
PHP 7.4.11
doublethreedigital/runway 2.3.0
doublethreedigital/simple-commerce 2.3.70

**Comment by duncanmcclean** [comment]
You don't need to find the views. Just make it go to Runway's URL.
