### ISSUE TITLE
Blueprint changes not making a difference

### ISSUE THREAD

**Issue by HazemMohamed252** [doublethreedigital/runway#131]
### What's the issue you're running into?

When i create blueprint for any resource using runway and try to edit this blueprint and remove the sidebar section after saving it display it again and not removed, how to force it to be removed ?

### Steps to reproduce

1. Create blueprint
2. Edit it and try to remove the sidebar section
3.  Click save

### Environment

Statamic 3.2.37 Pro
Laravel 8.83.4
PHP 7.4.11
doublethreedigital/runway 2.3.0

**Comment by duncanmcclean** [comment]
How are you saving your blueprint? Are you sure you're editing the right one?

The sidebar is hidden just fine for me if I remove it one of my resources.

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/19637309/158226483-8121aa87-035a-44ef-a5e4-aeedab78a897.png">

**Comment by HazemMohamed252** [comment]
Yes, i create a blueprint for the required resource under the page collection and when i open it to make any edits it always shows me the sidebar, how can i fix this ?

**Comment by duncanmcclean** [comment]
And what does your Runway config look like? My guess is you have different blueprint files configured for your resource than you're editing in the CP.

**Comment by HazemMohamed252** [comment]
![statamic](https://user-images.githubusercontent.com/29832976/158239083-9da1cf73-592a-43e1-bc34-55b5daf83b00.PNG)
This is my files on my editor. And another thing when i try to move the yaml file for any one of them out the collection it disappeared from th CP although i change the blueprint path in the runway config. Any way to handle this ?

**Comment by duncanmcclean** [comment]
Yes, it will disappear. Thats to be expected. You can't edit Runway blueprints in the CP yet, statamic limitation.

**Comment by HazemMohamed252** [comment]
So that is mean whatever i did the sidebar for runway blueprints still remains ? Because sometimes i don not need the sidebar for them

**Comment by duncanmcclean** [comment]
Sorry, I don't understand what you mean....

**Comment by HazemMohamed252** [comment]
I mean that whatever i do the sidebar for the runway blueprint will be sticky and can not be removed. Right ?

**Comment by duncanmcclean** [comment]
No, as I showed in my previous screenshot. You can get rid of the sidebar fine as long as it's not defined in your blueprint.

**Comment by HazemMohamed252** [comment]
Can you show me in your editor wher you put the blueprint yaml file, in your runway config where you call the blueprint file because whatever i do the sidebar always exists and i don not need it anymore

**Comment by HazemMohamed252** [comment]
![blueprints](https://user-images.githubusercontent.com/29832976/158347364-75550667-500b-4672-b9a9-8a4ef98906d6.PNG)
As you see my blueprints always show under collections section but when i edit on it it always show and in runway config file i put the path for any blueprint like : 
\App\Models\Categories::class => [
            'name' => 'Categories',
            'blueprint' => 'collections/pages/categories'
        ],
Any suggestion ?

**Comment by duncanmcclean** [comment]
Try moving your blueprint into `resources/blueprints` (not inside any other folders). Then in your config, reference it like this:

```php
'blueprint' => 'name-of-file-without-file-extension',
```

This [is covered in the Runway documentation](https://runway.duncanmcclean.com/resources#content-creating-a-new-blueprint).

**Comment by HazemMohamed252** [comment]
I did it as mentioned but nothing happened and it disappeared

**Comment by duncanmcclean** [comment]
Yes, it will disappear because Runway blueprints don't show in the Control Panel.
