### ISSUE TITLE
scopeRunwaySearch doesnt override default behaviour

### ISSUE THREAD

**Issue by ryanmitchell** [doublethreedigital/runway#149]
### Bug Description

When specifying a `scopeRunwaySearch` on my model I would expect it to override the default search behaviour that Runway provides. However, it seems that it provides[ search in **addition** to the default behaviour](https://github.com/doublethreedigital/runway/blob/7b9fcb97e677b5d29b7c4e04448fe548cb15fecd/src/Fieldtypes/BaseFieldtype.php#L90-L92).

This causes issues for our use case as it stops results being shown due to the subsequent `orWhere` clauses. 

There needs to be a way for the orWhere clauses not to be run

### Steps to reproduce

Should hopefully be sufficient detail in the description above.

### Environment

Statamic 3.3.12 Pro
Laravel 8.83.13
PHP 8.0.17
aerni/social-links 2.3.0
doublethreedigital/runway 2.3.5
jonassiewertsen/statamic-livewire 2.9.0
pecotamic/sitemap 1.4.0
statamic/eloquent-driver 0.2.0
statamic/seo-pro 3.1.0
thoughtco/statamic-minify 1.1.1
thoughtco/statamic-redirects 1.1.0

**Comment by duncanmcclean** [comment]
Good catch - I'd consider that a bug! Will see if I can get it fixed in the next few days for you! 👍
