### ISSUE TITLE
Listing Improvements

### ISSUE THREAD

**Issue by duncanmcclean** [doublethreedigital/runway#15]
There's a couple of improvements I'd like to make to the index listing:

* Ability for filters, just like the entries listing
* Real-time search (over AJAX, instead of full page reloads)
* Confirmation on the delete action #13
* Ability to use [Actions](https://statamic.dev/extending/actions#content) on the Runway listing #14 

I still need to investigate how this would work behind the scenes, especially with the filters..

## How should it work?

Will probably need to convert the index listing from Blade to Vue so I can do the real-time-ness that's required for some of the features.

## Use cases

Where you want to use Runway as a replacement for entries.

**Comment by ryanmitchell** [comment]
Just came across this repo - which is amazing - thank you. 

I'm pretty new to statamic but I spent some time building a custom/reusable listing view for our needs for a project we're working on at the moment. A lot of the features above are there, so I don't know if its useful as a starting point:
https://github.com/thoughtco/statamic-cplisting/blob/master/resources/js/components/CPListing.vue

**Comment by duncanmcclean** [comment]
> Just came across this repo - which is amazing - thank you.
> 
> I'm pretty new to statamic but I spent some time building a custom/reusable listing view for our needs for a project we're working on at the moment. A lot of the features above are there, so I don't know if its useful as a starting point:
> https://github.com/thoughtco/statamic-cplisting/blob/master/resources/js/components/CPListing.vue

Ah, nice. I'll take a look when I get round to working on this card. Thanks!

**Comment by ryanmitchell** [comment]
No prob. I’m sure you’re all over it but if it helps to see how I’ve used it in controllers / views just shout.
