### ISSUE TITLE
Error when a model is added to a field then deleted

### ISSUE THREAD

**Issue by ryanmitchell** [doublethreedigital/runway#156]
### Bug Description

When a model is added to a field then subsequently deleted, the tag returns an error such as:

`DoubleThreeDigital\Runway\Resource::augment(): Argument #1 ($model) must be of type Illuminate\Database\Eloquent\Model, null given, called in /home/ploi/site/vendor/doublethreedigital/runway/src/Fieldtypes/BaseFieldtype.php on line 195`

### Steps to reproduce

1. Add a resource
2. Add a model to the resource
3. Select the model in a field on a page
4. Delete the model from the resource
5. Output the contents of the field in antlers
6. Enjoy the error that meets you

### Environment

```
Statamic 3.3.16 Pro
Laravel 8.83.16
PHP 8.0.17
aerni/social-links 2.3.1
doublethreedigital/runway 2.3.9
jonassiewertsen/statamic-livewire 2.9.0
pecotamic/sitemap 1.4.0
statamic/eloquent-driver 0.2.0
statamic/seo-pro 3.1.0
thoughtco/statamic-minify 1.1.1
thoughtco/statamic-redirects 1.1.0
```

**Comment by duncanmcclean** [comment]
Good catch, we should probably filter out models that no longer exist from being augmented.

**Comment by ryanmitchell** [comment]
Thank you
