### ISSUE TITLE
Export to csv

### ISSUE THREAD

**Issue by freshface** [doublethreedigital/runway#18]
Possibility to export the entries to csv.

**Comment by duncanmcclean** [comment]
Just out of curiosity, what's your use case for this?

**Comment by freshface** [comment]
> Just out of curiosity, what's your use case for this?

I show subscriptions to an event.
And it would be nice to export that data to use in excel.

**Comment by duncanmcclean** [comment]
Ah gotcha. This isn't probably something I'll ever add as part of Runway. 

However, [Laravel Excel](https://docs.laravel-excel.com/3.1/getting-started/) is a great package for doing that kind of thing if you need it, I've used it a couple of times.

**Comment by freshface** [comment]
Is it easy to add to runway?
Or should i make a custom runway for myself with that funtionality?

**Comment by duncanmcclean** [comment]
That's a good question, I should probably add like an ability to add custom buttons to the listing page.... Leave that with me and I'll see what I can do.

**Comment by freshface** [comment]
Also the ability to apply custom filters to the eloquent model would be nice. To apply custom filtering/sorting via the ui :)

But maybe its a bit much.

**Comment by duncanmcclean** [comment]
Custom filtering is on the plan for whenever I get round to properly re-doing the listing page. But I don't have the time at the moment for doing that 😆

**Comment by duncanmcclean** [comment]
Alright, added it, here's the documentation: https://github.com/doublethreedigital/runway#listing-buttons

**Comment by duncanmcclean** [comment]
Also, I'm gonna close as it's not really something I'm planning on adding to Runway at this time.
