### ISSUE TITLE
Access Blueprint Builder Via CP

### ISSUE THREAD

**Issue by johncarter-** [doublethreedigital/runway#20]
## What would you like to see added?
Be able to use Statamic GUI to view and edit runway blueprints from the CP. I assume that is what this idea is about: https://github.com/statamic/ideas/issues/408

## Is there a workaround you can use in the meantime?
Yep - just do it manually.

## Would you be open to PR'ing the feature?
Yes.

**Comment by duncanmcclean** [comment]
Yeah, that's what that FR is about. One day I'll actually get round to PR'ing it into core. 😆

**Comment by johncarter-** [comment]
I know you're a busy man. No stress.

**Comment by duncanmcclean** [comment]
Closing this in favour of statamic/cms#3963. My guess is that it'll be merged in soon-ish so this isn't really a Runway issue anymore.
