### ISSUE TITLE
Creating a new model causes browser dirty state warning

### ISSUE THREAD

**Issue by johncarter-** [doublethreedigital/runway#41]
### Description

If you create a new model from e.g. https://statamic-runway-demo.test/cp/runway/mymodel/create

Chrome throws a dirty state warning ( I assume because of the pending redirect ):
![image](https://user-images.githubusercontent.com/3776888/123627994-8d7d3e00-d80a-11eb-9a62-b953843373e2.png)

### Steps to reproduce

1. Load up Chrome
2. Go to create a model
2. Add some data
3. Click save
4. See dirty state warning

### Environment

Statamic 3.1.26 Solo
Laravel 8.48.2
PHP 7.4.19
doublethreedigital/runway 2.0.5

**Comment by duncanmcclean** [comment]
Closed by #47
