### ISSUE TITLE
Support for GraphQL

### ISSUE THREAD

**Issue by goellner** [doublethreedigital/runway#54]
### What would you like to see added?

For headless sites with lots of entries, this could be the killer feature thats currently missing in Statamic. Being able to store some Collections in a database would be the perfect solution.

Would be great to be able to enable GraphQL for certain models. Sometimes we just add models that just hold data and shouldn't be publicly queryable.

### Is there a workaround you can use in the meantime?

Not that I can think of, is the data available in the content api? 

### Priority wise - where's this feature for you?

I'm going to need it at some point in the future but it's not major right now.

**Comment by duncanmcclean** [comment]
I know this issue has been open for a pretty long time at this point and I just wanted to let you know that this is still on my to-do list. If nothing bigger gets in the way, hopefully it'll be worked on in the next couple weeks.

I've never used GraphQL before so it'll be an interesting feature to try and add but I'll do the best I can 😅

**Comment by duncanmcclean** [comment]
After a long wait... GraphQL support has arrived (in [v2.1.27](https://github.com/doublethreedigital/runway/releases/tag/v2.1.27)! 

I've written up some documentation [over here](https://runway.duncanmcclean.com/graphql) so you can see how to enable it and start querying your models!
