### ISSUE TITLE
Content API

### ISSUE THREAD

**Issue by duncanmcclean** [doublethreedigital/runway#55]
### What would you like to see added?

It would be nice for this addon to bring support for the Statamic [Content API](https://statamic.dev/content-api#content).

If we implement #54, it makes sense we introduce this as well.

### Is there a workaround you can use in the meantime?

You could build your own API endpoints with Resources and just get the data out that way.

### Priority wise - where's this feature for you?

This is just a nice to have. I can deal without.

**Comment by duncanmcclean** [comment]
Closing this down for now as there's been no demand for it - if someone needs it 👋  and I'll re-open.

**Comment by Smef** [comment]
Ah, I was hoping this would be supported. We were needing to migrate some data from regular collections to their own table, but we're currently using the Content API to get that information. Unfortunately we wouldn't be able to move our stuff over to regular tables with Runway without the Content API. It would be great if this was supported!

**Comment by duncanmcclean** [comment]
You're free to create your own API controllers to return the data, just like normal Laravel.

**Comment by duncanmcclean** [comment]
This will be supported when Runway v6 is released, thanks to this PR: #356

(no ETA on v6 yet, however)

**Comment by Smef** [comment]
Very nice! This will make it easy to use Eloquent models alongside the regular Statamic Entries when using Statamic as a headless CMS.

Thanks!

**Comment by duncanmcclean** [comment]
Runway v6 has now been released, which includes a REST API! 🚀
