### ISSUE TITLE
HasRelation

### ISSUE THREAD

**Issue by andershagbard** [doublethreedigital/runway#73]
### What would you like to see added?

HasMany, HasOne etc.

### Is there a workaround you can use in the meantime?

Not sure.

### Priority wise - where's this feature for you?

This is just a nice to have. I can deal without.

**Comment by edalzell** [comment]
My use case is:

* building an Orphan portal, where folks can sponsor orphans in 3rd world countries
* In the DB Orphans HaveMany OrphanUpdates
* However we only one one Runway page, Orphan, and on there see the orphan details as well as all the related updates, maybe via the "stack" mechanism?

**Comment by duncanmcclean** [comment]
I've started work on building out a `HasMany` fieldtype, see #74 which will implement that side of things.

**Comment by edalzell** [comment]
@duncanmcclean this is actually the one I care about, not the other one, lol, sorry.

**Comment by duncanmcclean** [comment]
Added & released a HasMany fieldtype which should hopefully solve this issue, see [v2.1.21](https://github.com/doublethreedigital/runway/releases/tag/v2.1.21).

If you need any other fieldtypes, please open fresh issues 😃
