### ISSUE TITLE
HasMany field: ability to click and select columns

### ISSUE THREAD

**Issue by edalzell** [doublethreedigital/runway#76]
### What would you like to see added?

The new HasMany Fieldtype is great, thanks for this.

For our use case we'd like one of 2 things:

1. it to act like the Entries type, where you can click on the item and have the stack slide out.
2. be able to click on the item and get taken to its edit page, as well as being able to choose columns to see.

### Is there a workaround you can use in the meantime?

Nope, for our use case we can't use this field.

### Priority wise - where's this feature for you?

This is sort of a blocker for me/this project.

**Comment by duncanmcclean** [comment]
When you say `be able to click on the item and get taken to its edit page, as well as being able to choose columns to see.` - what do you mean by being able to choose the columns to see, do you mean in the stack selector?

**Comment by adnankussair** [comment]
> When you say `be able to click on the item and get taken to its edit page, as well as being able to choose columns to see.` - what do you mean by being able to choose the columns to see, do you mean in the stack selector?

@duncanmcclean - columns to see would be as in being able to add a status column to the "selector" so you can see which entries are open or closed. Being able to click on an entry would allow you to edit the entry without leaving the related entry that you are in.

**Comment by duncanmcclean** [comment]
@adnankussair Sorry to be a pain but what do you mean by being able to add a status column to the selector? Do you have a screenshot of what you mean on one of the other fieldtypes?

**Comment by edalzell** [comment]
> @adnankussair Sorry to be a pain but what do you mean by being able to add a status column to the selector? Do you have a screenshot of what you mean on one of the other fieldtypes?

@duncanmcclean what AK is talking about is only if we don't have the stack type (which would be our preference). With no slide out stack, we'd like to be able to choose which columns appear in the hasmany field type, can have a column be clickable so we can edit that entries.

I'll chat w/ you next week about our use case.

**Comment by adnankussair** [comment]
> > @adnankussair Sorry to be a pain but what do you mean by being able to add a status column to the selector? Do you have a screenshot of what you mean on one of the other fieldtypes?
> 
> @duncanmcclean what AK is talking about is only if we don't have the stack type (which would be our preference). With no slide out stack, we'd like to be able to choose which columns appear in the hasmany field type, can have a column be clickable so we can edit that entries.
> 
> I'll chat w/ you next week about our use case.

Thanks @edalzell

@duncanmcclean I was working on a mockup for you but never got around to finishing it on friday. Will try to get this over to you next week.

**Comment by duncanmcclean** [comment]
@edalzell @adnankussair It's your lucky day, just added stacks (the pop-out things) for creating/editing models via the Runway fieldtypes. Released in [v2.1.23](https://github.com/doublethreedigital/runway/releases/tag/v2.1.23)

**Comment by adnankussair** [comment]
@duncanmcclean You rock brotha. Thanks a bunch.
