### ISSUE TITLE
Delete button missing in CP after installing Runway

### ISSUE THREAD

**Issue by kimoxlund** [doublethreedigital/runway#79]
### Description

When I install Runway I'm somehow unable to delete any entries, taxonomies, or assets. The delete buttons are removed from tables and action dropdown. I can still delete blueprints and fieldsets. 

### Steps to reproduce

CP without Runway installed: 
<img width="285" alt="Screen Shot 2021-09-14 at 10 35 55 AM" src="https://user-images.githubusercontent.com/1178797/133312226-c5a76152-21a9-43bc-b155-479f430eefa5.png">

CP with Runway installed: 
<img width="309" alt="Screen Shot 2021-09-14 at 10 36 38 AM" src="https://user-images.githubusercontent.com/1178797/133312263-913f3aae-6ecb-46e6-9cd1-74e6987b8d07.png">

If I uninstall Runway the delete buttons come back. I have tried different combinations of Runway and Statamic versions, but they all give the same result. 

### Environment

Statamic 3.2.4 Solo
Laravel 8.61.0
PHP 7.4.12
doublethreedigital/runway 2.1.21

**Comment by duncanmcclean** [comment]
Huh, that's not very helpful, is it?

**Comment by kimoxlund** [comment]
Oh, that was fast. Fix works perfectly. Thanks!

**Comment by duncanmcclean** [comment]
No worries - I'll tag a proper release shortly!

**Comment by duncanmcclean** [comment]
Here we go... released in [v2.1.22](https://github.com/doublethreedigital/runway/releases/tag/v2.1.22)
