### ISSUE TITLE
Support query scopes

### ISSUE THREAD

**Issue by edalzell** [doublethreedigital/runway#82]
### What would you like to see added?

My use case:

- `OprhanUpdate` model
- OrphanUpdate has a `since(...carbon...)` query scope that returns updates since a given date

I'd love to be able to run that query scope (and potentially more than one query scope) in Antlers like so:

```
{{ runway:orphanupdate scope="since:some_date" where="...." }}
```

Should also support multiple query scopes, perhaps like `scopes="since:some_date|another_scope"`?

### Is there a workaround you can use in the meantime?

custom modifiers

### Priority wise - where's this feature for you?

This is just a nice to have. I can deal without.

**Comment by duncanmcclean** [comment]
For my reference when I come back to this issue, probably later today or tomorrow: https://statamic.dev/tags/collection#custom-query-scopes
